#!/usr/bin/env bash

set -o nounset
set -o errexit

SECURITY_GROUP_GROUP_ID=$(
  aws ec2 create-security-group \
    --group-name "${SECURITY_GROUP_NAME}" \
    --description "${SECURITY_GROUP_DESCRIPTION}" \
    --query "GroupId" \
    --output text
)

# authorize port 22 for SSH
aws ec2 authorize-security-group-ingress \
  --group-id "${SECURITY_GROUP_GROUP_ID}" \
  --protocol tcp \
  --port 22 \
  --cidr "${SECURITY_GROUP_ALLOWED_CIDR}"

# authorize port 3389 for RDP
aws ec2 authorize-security-group-ingress \
  --group-id "${SECURITY_GROUP_GROUP_ID}" \
  --protocol tcp \
  --port 3389 \
  --cidr "${SECURITY_GROUP_ALLOWED_CIDR}"

printf "\n{\n  \"GroupId\": \"%s\"\n}\n" "${SECURITY_GROUP_GROUP_ID}"

