#!/usr/bin/env bash

set -o nounset
set -o errexit

KEY_NAME="${1}"

aws ec2 create-key-pair \
  --key-name "${KEY_NAME}" \
  --query "KeyMaterial" \
  --output text \
  > "${KEY_NAME}.pem"

chmod 0400 "${KEY_NAME}.pem"
